language:
  - cpp
  - python

cpp: c++11

python: "3.8"

compiler: g++

before_install:
  - sudo apt-get update
  - sudo apt-get install -y doxygen 

install:
  - cd ~/
  - mkdir include
  - git clone https://github.com/simongog/sdsl-lite.git
  - git clone https://github.com/martinmoene/lest.git
  - cd sdsl-lite
  - ./install.sh
  - cd ../
  - cp -r ./sdsl-lite/include/sdsl ./include
  - cp -r ./lest/include/lest ./include
  - git clone --recurse-submodules https://github.com/yoann-dufresne/ConwayBromageLib.git

script:
  - cd $TRAVIS_BUILD_DIR  #dossier où est contenu notre code
  - doxygen Doxyfile      #génération de la documentation dans le dossier doc/
  - cd ConwayBromageLib
  - python3 involveGenerate_counts.py -k 4 -n 100 -f ACTG > unsortACTG.txt
  - python3 involveGenerate_counts.py -k 4 -n 100 -f ACGT > unsortACGT.txt
  - sort unsortACGT.txt > sortACGT.txt
  - python3 sortACTG.py unsortACTG.txt > sortACTG.txt
  # don't use cmake for tests
  - g++ -Wall -Wextra -std=c++11 -Dlest_FEATURE_AUTO_REGISTER=1 -Dlest_FEATURE_COLOURISE=1 -O3 -DNDEBUG -I ~/include -L ~/lib -o ConwayBromageLib Tests.cpp ConwayBromageLib.cpp -lsdsl -ldivsufsort -ldivsufsort64
  - ./ConwayBromageLib
  
  
