language: 
  - cpp
  - python

cpp: c++11

python: "3.6"

compiler: g++

#before_install: |
#  if ! [ -f sdsl-lite/ ]; then
#    git clone https://github.com/simongog/sdsl-lite.git;
#    cd sdsl-lite/;
#    ./install.sh;
#  fi

#cache:
#  directories:
#    - sdsl-lite/

install:
  - git clone https://github.com/simongog/sdsl-lite.git
  - cd sdsl-lite
  - ./install.sh
  - cd ../
  - git clone https://github.com/martinmoene/lest.git

script:
  - cd $TRAVIS_BUILD_DIR #là où est contenu notre code ( pas  sdsl-lite )
  - python3 gen.py -k 2 -n 16 | sort > sorted_kmers.txt
  - g++ -Wall -Wextra -std=c++11 -Dlest_FEATURE_AUTO_REGISTER=1 -Dlest_FEATURE_COLOURISE=1 -O3 -DNDEBUG -I ~/include -L ~/lib -o Tests.exe Tests.cpp ConwayBromageLib.cpp -lsdsl -ldivsufsort -ldivsufsort64
  - ./Tests.exe 
